spring.application.name=PilotLogbook

# ===== DataSource (PostgreSQL) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/pilotlogbook
spring.datasource.username=pilot
spring.datasource.password=pilot_password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===== Server =====
server.port=8080

# ===== JWT =====
jwt.secret=l3hRi4hSW++t9bR+9/GV4WoZfBoLWqmTkl75pX1+T1g=
jwt.expiration-ms=86400000

